import { Shield, Users, TrendingUp, MessageSquare, Target, FileText, Crown, Rocket, Activity, Zap, Library, Sparkles, BarChart3 } from "lucide-react";

// ─── SEO Meta ───────────────────────────────────────────────────────────────────
export const SEO = {
  en: {
    title: "AI Career Transformation & Executive Coaching | MA-TRAINING-CONSULTING",
    description: "The world's first AI+Human ecosystem for career diagnostics, executive simulations, and strategic growth. Get your DIGNNOS™ certification and a 24/7 AI Strategic Mentor.",
    keywords: "AI career guidance, executive coaching, professional roadmap, job simulation, HR consulting, strategic role audit, MATC",
  },
  fr: {
    title: "Transformation de Carrière IA & Coaching Exécutif | MA-TRAINING-CONSULTING",
    description: "Le premier écosystème IA+Humain pour le diagnostic de carrière, les simulations exécutives et la croissance stratégique. Obtenez votre certification DIGNNOS™.",
    keywords: "conseiller IA, coaching exécutif, feuille de route stratégique, simulation emploi, audit RH, diagnostic carrière",
  },
  ar: {
    title: "التحول المهني بالذكاء الاصطناعي والتدريب التنفيذي | MA-TRAINING-CONSULTING",
    description: "أول نظام بيئي متكامل (ذكاء اصطناعي + بشري) للتشخيص المهني، المحاكاة التنفيذية، والنمو الاستراتيجي. احصل على شهادة DIGNNOS™ ومستشار ذكي 24/7.",
    keywords: "مستشار ذكي, تدريب تنفيذي, خارطة طريق استراتيجية, محاكاة وظيفة, استشارات HR, تدقيق الدور الاستراتيجي",
  },
};

// ─── HERO ────────────────────────────────────────────────────────────────────────
export const HERO = {
  en: {
    badge: "Scholarship & Job Seeker Mission",
    title: "Your Future Identity is",
    titleHighlight: "Generated by AI Mastery",
    subtitle: "Navigate your entry into the job market with the world's most powerful diagnostic engine. We don't just offer tools—we generate an entire ecosystem of mentorship and 80% personalized workshops born directly from your diagnostic DNA.",
    ctaPrimary: "Execute Diagnostic Engine",
    ctaSecondary: "Explore the Generation Map",
    stats: [
      { value: "07", label: "Diagnostic Stages" },
      { value: "80%", label: "Workshop Personalization" },
      { value: "24/7", label: "Generated AI Mentor" },
      { value: "DIGNNOS™", label: "Authority Proof" },
    ],
  },
  fr: {
    badge: "Mission Bourse & Chercheur d'Emploi",
    title: "Votre Identité Professionnelle est",
    titleHighlight: "Générée par l'IA Stratégique",
    subtitle: "Pilotez votre insertion professionnelle avec le moteur de diagnostic le plus puissant au monde. Nous ne proposons pas d'outils—nous générons tout un écosystème de mentorat et de workshops personnalisés à 80% nés de votre ADN diagnostic.",
    ctaPrimary: "Lancer le Moteur Diagnostic",
    ctaSecondary: "Explorer la Génération",
    stats: [
      { value: "07", label: "Étapes Diagnostic" },
      { value: "80%", label: "Personnalisation Ateliers" },
      { value: "24/7", label: "Mentor IA Généré" },
      { value: "DIGNNOS™", label: "Preuve d'Autorité" },
    ],
  },
  ar: {
    badge: "باقة المنحة لفرص العمل",
    title: "هويتك المهنية المستقبلية هي",
    titleHighlight: "نتاج توليد الذكاء الاستراتيجي",
    subtitle: "قُد رحلة دخولك لسوق العمل عبر أقوى محرك تشخيص في العالم. نحن لا نقدم أدوات مجردة، بل نولّد لك نظاماً كاملاً من التوجيه وورش العمل المخصصة بنسبة 80%، والتي تولد جميعها من الحمض النووي لتشخيصك.",
    ctaPrimary: "تفعيل محرك التشخيص",
    ctaSecondary: "خارطة طريق التوليد الذكي",
    stats: [
      { value: "٠٧", label: "مراحل التشخيص" },
      { value: "٨٠٪", label: "تخصيص ورش العمل" },
      { value: "٢٤/٧", label: "مستشار ذكي مولّد" },
      { value: "DIGNNOS™", label: "سلطة مهنية موثقة" },
    ],
  },
};

// ─── PROBLEM ─────────────────────────────────────────────────────────────────────
export const PROBLEM = {
  en: {
    badge: "The Career Barrier",
    title: "Why New Talents Stay Hidden",
    points: [
      { icon: "📉", text: "Degrees alone no longer prove execution potential in a fierce market." },
      { icon: "🌫️", text: "Generic job applications that never reach the final decision-makers." },
      { icon: "📜", text: "Identity documents (CVs) that lack the strategic depth required by modern AI." },
      { icon: "🛑", text: "Walking into interviews without a verified authority proof (DIGNNOS™)." },
    ],
    solution: "The Diagnostic is the only way out. It identifies exactly what's missing and generates the fix instantly.",
  },
  fr: {
    badge: "La Barrière de Carrière",
    title: "Pourquoi les Jeunes Talents restent Invisibles",
    points: [
      { icon: "📉", text: "Le diplôme seul ne prouve plus le potentiel d'exécution en entreprise." },
      { icon: "🌫️", text: "Des candidatures génériques qui n'atteignent jamais les vrais décideurs." },
      { icon: "📜", text: "Des CV qui manquent de la profondeur stratégique exigée par l'IA moderne." },
      { icon: "🛑", text: "Aller en entretien sans preuve d'autorité vérifiée (DIGNNOS™)." },
    ],
    solution: "Le Diagnostic est la seule issue. Il identifie les failles et génère la solution instantanément.",
  },
  ar: {
    badge: "حاجز المسار المهني",
    title: "لماذا تبقى المواهب الجديدة مخفية؟",
    points: [
      { icon: "📉", text: "الشهادات الأكاديمية وحدها لم تعد كافية لإثبات الجدارة في سوق شرس." },
      { icon: "🌫️", text: "طلبات توظيف تقليدية لا تصل أبداً إلى أصحاب القرار الحقيقيين." },
      { icon: "📜", text: "سير ذاتية تفتقر للعمق الاستراتيجي الذي تطلبه أنظمة الفرز الذكية." },
      { icon: "🛑", text: "دخول مقابلات العمل دون امتلاك سلطة مهنية موثوقة (DIGNNOS™)." },
    ],
    solution: "التشخيص هو الحل الوحيد. هو الذي يحدد بدقة ما ينقصك ويولّد لك العلاج فوراً.",
  },
};

// ─── THE 7-STAGE AI JOURNEY ──────────────────────────────────────────────────────
export const JOURNEY = {
  en: {
    badge: "The Diagnostic Core",
    title: "The Engine of Your Future",
    subtitle: "Everything begins here. The Diagnostic isn't just a step; it's the DNA from which your entire ecosystem is born.",
    steps: [
      { id: "01", title: "AI CV Intelligence", desc: "Digital extraction of your potential and market positioning.", icon: FileText, color: "blue", tag: "Analysis" },
      { id: "02", title: "Strategic AI Interview", desc: "A deep verification of your skills to define your future modules.", icon: MessageSquare, color: "purple", tag: "Verification" },
      { id: "03", title: "The Verdict & Creation", desc: "Your diagnostic verdict is reached, triggering the birth of your personalized ecosystem.", icon: Activity, color: "emerald", tag: "Birth" },
      { id: "04", title: "Module Generation", desc: "Your Mentor, Library, and Roadmap are instantly generated based on your SCI report.", icon: Zap, color: "orange", tag: "Generation" },
      { id: "05", title: "80% Personalized Workshops", desc: "Highly specific workshops designed to fix the gaps found in your diagnostic.", icon: Users, color: "pink", tag: "Growth" },
      { id: "06", title: "Professional Architecture", desc: "Building your high-impact identity documents (ATS Optimized).", icon: FileText, color: "cyan", tag: "Identity" },
      { id: "07", title: "Strategic Simulation", desc: "Only after analysis: A final mission to prove your readiness and earn certification.", icon: Crown, color: "amber", tag: "Authority" },
    ]
  },
  fr: {
    badge: "Le Cœur du Diagnostic",
    title: "Le Moteur de Votre Avenir",
    subtitle: "Tout commence ici. Le Diagnostic est l'ADN à partir duquel tout votre écosystème prend vie.",
    steps: [
      { id: "01", title: "Intelligence CV IA", desc: "Extraction numérique de votre potentiel et audit de marché.", icon: FileText, color: "blue", tag: "Analyse" },
      { id: "02", title: "Entretien Stratégique IA", desc: "Vérification profonde de vos compétences pour définir vos modules.", icon: MessageSquare, color: "purple", tag: "Vérification" },
      { id: "03", title: "Verdict & Création", desc: "Le verdict tombe, déclenchant la naissance de votre écosystème perso.", icon: Activity, color: "emerald", tag: "Naissance" },
      { id: "04", title: "Génération de Modules", desc: "Votre Mentor, Bibliothèque et Roadmap sont générés selon votre rapport SCI.", icon: Zap, color: "orange", tag: "Génération" },
      { id: "05", title: "Workshops 80% Personnalisés", desc: "Ateliers spécifiques conçus pour corriger vos lacunes diagnostiquées.", icon: Users, color: "pink", tag: "Croissance" },
      { id: "06", title: "Architecture Pro", desc: "Construction de vos documents d'identité à haut impact (ATS Optimisé).", icon: FileText, color: "cyan", tag: "Identité" },
      { id: "07", title: "Simulation Stratégique", desc: "Après analyse : Mission finale pour prouver votre readiness et être certifié.", icon: Crown, color: "amber", tag: "Autorité" },
    ]
  },
  ar: {
    badge: "جوهر التشخيص",
    title: "المحرك الذي يصنع مستقبلك",
    subtitle: "كل شيء يبدأ من هنا. التشخيص ليس مجرد خطوة؛ بل هو الحمض النووي (DNA) الذي يولد منه نظامك المتكامل.",
    steps: [
      { id: "٠١", title: "ذكاء السيرة الذاتية", desc: "استخراج رقمي لقدراتك وتدقيق موقعك في السوق.", icon: FileText, color: "blue", tag: "تحليل" },
      { id: "٠٢", title: "المقابلة الاستراتيجية", desc: "تحقق عميق من مهاراتك لتحديد ملامح وحدات التدريب القادمة.", icon: MessageSquare, color: "purple", tag: "تحقق" },
      { id: "٠٣", title: "قرار التشخيص والميلاد", desc: "صدور الحكم التشخيصي، الذي يفجّر ميلاد نظامك الشخصي المتكامل.", icon: Activity, color: "emerald", tag: "ميلاد" },
      { id: "٠٤", title: "توليد الوحدات (Generation)", desc: "مولد المستشار، المكتبة، وخارطة الطريق فوراً بناءً على تقرير SCI الخاص بك.", icon: Zap, color: "orange", tag: "توليد" },
      { id: "٠٥", title: "ورش عمل مخصصة بنسبة ٨٠٪", desc: "ورش عمل مصممة خصيصاً لسد الفجوات التي كشفها التشخيص.", icon: Users, color: "pink", tag: "نمو" },
      { id: "٠٦", title: "الهندسة المهنية", desc: "بناء وثائق هويتك المهنية عالية التأثير (ATS Optimized).", icon: FileText, color: "cyan", tag: "هوية" },
      { id: "٠٧", title: "المحاكاة الاستراتيجية", desc: "بعد التحليل فقط: مهمة نهائية لإثبات جاهزيتك والحصول على الاعتماد.", icon: Crown, color: "amber", tag: "سلطة" },
    ]
  }
};

// ─── THE ADVANCED AI ECOSYSTEM ──────────────────────────────────────────────────
export const ECOSYSTEM_MODULES = {
  en: {
    badge: "Generated Ecosystem",
    title: "Modules Born From Diagnosis",
    subtitle: "Your results trigger the activation of specialized tools tailored to your specific profile.",
    modules: [
      { icon: Sparkles, title: "AI Strategic Mentor", desc: "Born from your SCI results to provide 24/7 tactical support for your growth.", link: "/mentor" },
      { icon: Library, title: "Curated Knowledge", desc: "A library of resources automatically filtered to match your skill gaps.", link: "/library" },
      { icon: TrendingUp, title: "🚀 Dynamic Roadmap", desc: "A transformation plan that evolves as you complete personalized workshops.", link: "/roadmap" },
      { icon: MessageSquare, title: "🔥 Specialist AI Chats", desc: "Expert agents triggered to help you master identified weak points.", link: "/expert" },
      { icon: BarChart3, title: "The Master SCI Report", desc: "The source document that anchors your entire professional journey.", link: "/strategic-report" },
      { icon: Users, title: "Targeted Workshops", desc: "80% personalized sessions focused on fixing your diagnostic-revealed gaps.", link: "/library" },
    ]
  },
  fr: {
    badge: "Écosystème Généré",
    title: "Modules Nés du Diagnostic",
    subtitle: "Vos résultats déclenchent l'activation d'outils spécialisés adaptés à votre profil.",
    modules: [
      { icon: Sparkles, title: "Mentor Stratégique IA", desc: "Né de vos résultats SCI pour un support tactique 24/7 pour votre croissance.", link: "/mentor" },
      { icon: Library, title: "Savoir Curaté", desc: "Une bibliothèque de ressources filtrée selon vos lacunes de compétences.", link: "/library" },
      { icon: TrendingUp, title: "🚀 Roadmap Dynamique", desc: "Un plan de transformation qui évolue avec vos workshops personnalisés.", link: "/roadmap" },
      { icon: MessageSquare, title: "🔥 Experten IA", desc: "Agents experts activés pour vous aider à maîtriser vos points faibles.", link: "/expert" },
      { icon: BarChart3, title: "Rapport Maître SCI", desc: "Le document source qui ancre tout votre parcours professionnel.", link: "/strategic-report" },
      { icon: Users, title: "Workshops Ciblés", desc: "Sessions personnalisées à 80% pour corriger les failles du diagnostic.", link: "/library" },
    ]
  },
  ar: {
    badge: "النظام البيئي المولّد",
    title: "وحدات تولد من استنتاجات التشخيص",
    subtitle: "نتائج تشخيصك هي التي تطلق تفعيل الأدوات المتخصصة المصممة لبروفايلك.",
    modules: [
      { icon: Sparkles, title: "المستشار الاستراتيجي الذكي", desc: "يولد من نتائج تقرير SCI لتقديم دعم تكتيكي لنموك 24/7.", link: "/mentor" },
      { icon: Library, title: "المعرفة المنسقة", desc: "مكتبة موارد تتم فلترتها تلقائياً لتناسب فجواتك المهارية.", link: "/library" },
      { icon: TrendingUp, title: "🚀 خارطة طريق ديناميكية", desc: "خطة تحول تتطور مع إتمامك لورش العمل المخصصة.", link: "/roadmap" },
      { icon: MessageSquare, title: "🔥 حوارات الخبراء", desc: "عملاء خبراء يتم تفعيلهم لمساعدتك في إتقان نقاط الضعف المحددة.", link: "/expert" },
      { icon: BarChart3, title: "تقرير SCI القائد", desc: "الوثيقة المصدر التي ترتكز عليها رحلتك المهنية بالكامل.", link: "/strategic-report" },
      { icon: Users, title: "ورش عمل مستهدفة", desc: "جلسات مخصصة بنسبة 80% تركز على إصلاح ثغراتك المكتشفة.", link: "/library" },
    ]
  }
};

// ─── HUMAN-LED MODULES ───────────────────────────────────────────────────────────
// ─── HUMAN INTEGRATION & WORKSHOPS ───────────────────────────────────────────────
export const HUMAN = {
  en: {
    badge: "Accelerated Growth",
    title: "The Workshop Personalization Engine",
    subtitle: "We don't do generic training. Our human-led interventions are 80% tailored based on your diagnostic gaps.",
    items: [
      { icon: Users, badge: "80% Personalized", title: "Targeted Strategic Workshops", desc: "Live sessions that don't waste time. Every workshop is contextually adjusted to fix the gaps identified in your 7-stage diagnostic." },
      { icon: Zap, badge: "The Ultimate Proof", title: "DIGNNOS™ Strategic Missions", desc: "Simulation scenarios born from your specific growth needs. Prove your competence in high-pressure interactive environments." },
      { icon: Rocket, badge: "Activation", title: "🚀 Roadmap Support", desc: "Dedicated experts help you activate the roadmap generated by the AI, ensuring execution in the real job market." },
      { icon: TrendingUp, badge: "Generation Quality", title: "Human Validation", desc: "Every AI-generated module and roadmap is nuanced by a human consultant for 100% market relevance." },
    ]
  },
  fr: {
    badge: "Croissance Accélérée",
    title: "Le Moteur de Personnalisation",
    subtitle: "Pas de formation générique. Nos interventions humaines sont à 80% sur mesure selon vos failles diagnostiquées.",
    items: [
      { icon: Users, badge: "80% Personnalisé", title: "Workshops Stratégiques Ciblés", desc: "Sessions live sans perte de temps. Chaque atelier est ajusté pour corriger les lacunes identifiées lors de votre diagnostic." },
      { icon: Zap, badge: "Preuve Ultime", title: "Missions Stratégiques DIGNNOS™", desc: "Des scénarios de simulation nés de vos besoins de croissance spécifiques. Prouvez votre talent sous pression." },
      { icon: Rocket, badge: "Activation", title: "🚀 Accompagnement Roadmap", desc: "Nos experts vous aident à activer la roadmap générée par l'IA pour garantir une exécution réelle sur le marché." },
      { icon: TrendingUp, badge: "Génération Qualité", title: "Validation Humaine", desc: "Chaque module et roadmap généré par l'IA est affiné par un consultant humain pour une pertinence marché totale." },
    ]
  },
  ar: {
    badge: "نمو متسارع",
    title: "محرك تخصيص ورش العمل",
    subtitle: "لا وجود للتدريب التقليدي العام. تدخلات خبرائنا مخصصة بنسبة 80% بناءً على الفجوات التي كشفها تشخيصك.",
    items: [
      { icon: Users, badge: "تخصيص بنسبة ٨٠٪", title: "ورش العمل الاستراتيجية المستهدفة", desc: "جلسات مباشرة لا تضيع وقتك. كل ورشة عمل يتم تعديلها سياقياً لإصلاح الفجوات المحددة في مراحل تشخيصك الـ 7." },
      { icon: Zap, badge: "الإثبات النهائي", title: "مهام DIGNNOS™ الاستراتيجية", desc: "سيناريوهات محاكاة تولد من احتياجات نموك الخاصة. أثبت جدارتك في بيئة عمل تفاعلية تحت الضغط." },
      { icon: Rocket, badge: "التفعيل", title: "دعم خارطة الطريق", desc: "يساعدك خبراؤنا في تفعيل خارطة الطريق التي ولدها الذكاء الاصطناعي، لضمان التنفيذ الفعلي في سوق العمل." },
      { icon: TrendingUp, badge: "جودة التوليد", title: "التصديق البشري الذكي", desc: "كل وحدة تدريبية أو خارطة طريق يولدها النظام تخضع لتدقيق وتحسين من مستشار بشري لضمان مطابقتها لواقع السوق." },
    ]
  }
};

// ─── CORPORATE SOLUTIONS (HR & COMPANY) ─────────────────────────────────────────
// ─── THE MATURATION PROCESS ──────────────────────────────────────────────────────
export const CORPORATE = {
  en: {
    badge: "The Maturation Path",
    title: "Authority Takes Time",
    description: "Your professional authority isn't bought—it's earned. Our ecosystem follows a 90-day maturation process to ensure your verified status in the market.",
    features: [
      "Initial 7-Stage Diagnostic Engine",
      "Instant AI Module Generation",
      "80% Personalized Workshop Series",
      "90-Day Authority Maturation period",
      "Final Official Recommendation & DIGNNOS™ Proof"
    ],
    cta: "Start Your Maturation Path"
  },
  fr: {
    badge: "Le Processus de Maturation",
    title: "L'Autorité Se Mérite",
    description: "Votre autorité professionnelle ne s'achète pas—elle se mérite. Notre écosystème suit un processus de 90 jours pour garantir votre statut vérifié.",
    features: [
      "Moteur Diagnostic en 7 Étapes",
      "Génération Instantanée des Modules IA",
      "Série de Workshops 80% Personnalisés",
      "Période de Maturation d'Autorité de 90 jours",
      "Recommandation Officielle & Preuve DIGNNOS™"
    ],
    cta: "Démarrer Votre Maturation"
  },
  ar: {
    badge: "مسار نضج الخبرة",
    title: "السلطة المهنية تُبنى بالوقت",
    description: "سلطتك المهنية لا تُشترى، بل تُكتسب. يتبع نظامنا مسار نضج يستغرق 90 يوماً لضمان حصولك على مكانة موثوقة في سوق العمل.",
    features: [
      "محرك التشخيص الأولي بـ 7 مراحل",
      "التوليد الفوري لوحدات الذكاء الاصطناعي",
      "سلسلة ورش عمل مخصصة بنسبة 80%",
      "فترة نضج الخبرة لمدة 90 يوماً",
      "خطاب التوصية الرسمي وإثبات DIGNNOS™ النهائي"
    ],
    cta: "ابدأ مسار النضج المهني"
  }
};

// ─── BENEFITS ────────────────────────────────────────────────────────────────────
export const BENEFITS = {
  en: {
    badge: "The Value",
    title: "Why Trust the DIGNNOS™ Model?",
    items: [
      { icon: Shield, title: "Identity Authority", desc: "Transform from a 'candidate' to a 'verified expert' with credentials recruiters trust." },
      { icon: Rocket, title: "Zero Guesswork", desc: "Your 18-month roadmap is generated by AI to fix your specific career gaps instantly." },
      { icon: Target, title: "80% Tailored Growth", desc: "Our workshops aren't generic—they are contextually adjusted to your diagnostic results." },
    ]
  },
  fr: {
    badge: "La Valeur",
    title: "Pourquoi faire confiance au modèle DIGNNOS™ ?",
    items: [
      { icon: Shield, title: "Autorité d'Identité", desc: "Passez de 'candidat' à 'expert vérifié' avec des documents certifiés." },
      { icon: Rocket, title: "Zéro Incertitude", desc: "Votre roadmap sur 18 mois est générée pour corriger vos failles spécifiques." },
      { icon: Target, title: "Croissance sur mesure", desc: "Nos workshops ne sont pas génériques—ils s'adaptent à 80% à vos résultats." },
    ]
  },
  ar: {
    badge: "القيمة المضافة",
    title: "لماذا تختار نموذج DIGNNOS™؟",
    items: [
      { icon: Shield, title: "مرجعية الهوية", desc: "تحول من 'مجرد مرشح' إلى 'خبير موثق' بوثائق تفرض الاحترام." },
      { icon: Rocket, title: "يقين مطلق", desc: "خارطة طريقك لـ 18 شهراً يتم توليدها فوراً لسد فجواتك المهنية بدقة." },
      { icon: Target, title: "نمو مخصص بنسبة ٨٠٪", desc: "ورش عملنا ليست عامة؛ بل يتم تعديل محتواها ليتناسب مع نتائج تشخيصك." },
    ]
  }
};

// ─── OFFICIAL GENERATED ASSETS ──────────────────────────────────────────────────
export const ASSETS = {
  en: {
    badge: "Generated Portfolio",
    subtitle: "Your Scientific Authority Docs",
    items: [
      { icon: BarChart3, title: "Master SCI Report", desc: "The definitive analysis born from your 7-stage diagnostic analysis." },
      { icon: FileText, title: "Recommendation Letter", desc: "Expert endorsement unlocked after the 90-day workshop maturation phase." },
      { icon: Users, title: "Workshop Certification", desc: "Official participation proof for workshops tailored 80% to your needs." },
      { icon: TrendingUp, title: "🚀 Generated Roadmap", desc: "A detailed 18-month execution plan born from your diagnostic DNA." },
      { icon: Zap, title: "Performance Scorecard", desc: "Proved readiness through strategic simulations executed post-analysis." },
      { icon: Target, title: "Precision Audit", desc: "A market-ready audit benchmarking your profile against top global standards." },
    ]
  },
  fr: {
    badge: "Portfolio Généré",
    subtitle: "Vos Documents d'Autorité Scientifique",
    items: [
      { icon: BarChart3, title: "Rapport Maître SCI", desc: "L'analyse définitive née de votre diagnostic en 7 étapes." },
      { icon: FileText, title: "Lettre de Recommandation", desc: "Endossement expert débloqué après 90 jours de maturation." },
      { icon: Users, title: "Certification Workshop", desc: "Preuve de participation aux ateliers personnalisés à 80%." },
      { icon: TrendingUp, title: "🚀 Roadmap Générée", desc: "Un plan de 18 mois né directement de votre ADN diagnostic." },
      { icon: Zap, title: "Performance Scorecard", desc: "Preuve de préparation via des simulations stratégiques post-analyse." },
      { icon: Target, title: "Audit de Précision", desc: "Un audit comparant votre profil aux standards mondiaux du marché." },
    ]
  },
  ar: {
    badge: "حقيبة الوثائق المولّدة",
    subtitle: "وثائق السلطة العلمية والمهنية",
    items: [
      { icon: BarChart3, title: "تقرير SCI القائد", desc: "التحليل النهائي والمفصل الناتج عن تشخيصك بـ 7 مراحل." },
      { icon: FileText, title: "خطاب التوصية الرسمي", desc: "تزكية الخبراء التي تفتح بعد فترة نضج الخبرة (90 يوماً)." },
      { icon: Users, title: "شهادة ورش العمل", desc: "إثبات رسمي للمشاركة في ورش العمل المخصصة بنسبة 80% لاحتياجاتك." },
      { icon: TrendingUp, title: "🚀 خارطة الطريق المولّدة", desc: "خطة تنفيذية لـ 18 شهراً تنبع مباشرة من الحمض النووي لتشخيصك." },
      { icon: Zap, title: "بطاقة الأداء (Scorecard)", desc: "إثبات الجاهزية عبر مهام محاكاة استراتيجية تُنفذ بعد التحليل." },
      { icon: Target, title: "تدقيق الجاهزية السوقية", desc: "تقرير تدقيق يقيس ملفك الشخصي مقابل أعلى المعايير العالمية." },
    ]
  }
};

// ─── PRICING ─────────────────────────────────────────────────────────────────────
export const PRICING = {
  en: {
    badge: "Investment",
    title: "Pricing Plans",
    subtitle: "Choose the level of support that fits your professional goals.",
    plans: [
      {
        name: "Discovery Trial",
        price: "Free",
        annualPrice: "Free",
        annualNote: "No credit card required",
        period: "Fully Free",
        desc: "Test the engine power with a preliminary skill extraction.",
        features: [
          "Free Professional Profile",
          "Initial CV Analysis & Summary",
          "Workshop Recommendations",
          "Preliminary Strategic Roadmap",
          "Community Access (Alfaida)"
        ],
        notIncluded: ["Full SCI Report", "AI Strategic Mentor", "80% Personalized Workshops"],
        cta: "Start Free Trial",
        color: "slate",
        icon: "🌱"
      },
      {
        name: "Scholarship Path",
        price: "Free*",
        annualPrice: "Free",
        annualNote: "Maturation period required",
        period: "Job Seeker / Student",
        popular: true,
        highlight: true,
        desc: "The full generative ecosystem for those building their first identity.",
        features: [
          "Full 7-Stage Diagnostic Engine",
          "Generated AI Strategic Mentor (Learned from SCI)",
          "80% Personalized Workshops (Post-Diagnostic)",
          "18-Month Dynamic Roadmap Generation",
          "Credential Unlocking after 90-day Maturation",
          "Strategic Simulations for Scorecard Performance"
        ],
        notIncluded: ["Instant Immediate Documents", "Dedicated 1:1 Human Consultant"],
        cta: "Activate Scholarship",
        color: "emerald",
        icon: "🎓"
      },
      {
        name: "Elite Authority",
        price: "$45",
        annualPrice: "$160/yr",
        annualNote: "Advanced execution support",
        period: "/ 3 months",
        desc: "For those ready to command the market with immediate power.",
        features: [
          "Everything in Scholarship Path",
          "Immediate Document Architecture",
          "Deep Specialist AI Experts Access",
          "Knowledge Archives (Filtered for gaps)",
          "Direct Human Validation of Roadmap",
          "Premium Authority Certification"
        ],
        notIncluded: ["Custom Corporate Training"],
        cta: "Claim Authority",
        color: "blue",
        icon: "💎"
      }
    ],
    extras: {
      title: "Strategic Add-ons",
      subtitle: "Customize your growth path with targeted expert interventions.",
      items: [
        { name: "Single Strategic Mission", desc: "High-pressure executive mission", price: "$99" },
        { name: "Deep Audit Session", desc: "1:1 with Senior Consultant", price: "$199" },
        { name: "CV Architecture", desc: "Professional ATS rewrite", price: "$79" },
      ]
    },
    paymentMethods: {
      title: "Secure & Flexible Payment",
      options: ["Bank Transfer (Tunisia & Global)", "International Card", "Corporate Billing"]
    },
    paymentNote: "All transactions are secured with military-grade encryption."
  },
  fr: {
    badge: "Investissement",
    title: "Plans Tarifaires",
    subtitle: "Choisissez le niveau d'accompagnement qui correspond à vos objectifs.",
    plans: [
      {
        name: "Essai Découverte",
        price: "Gratuit",
        annualPrice: "Gratuit",
        annualNote: "Sans carte de crédit",
        period: "Totalement Gratuit",
        desc: "Testez la puissance du moteur avec une extraction de base.",
        features: [
          "Profil Professionnel Gratuit",
          "Analyse CV Initiale & Résumé",
          "Suggestions de Workshops",
          "Roadmap Stratégique Préliminaire",
          "Accès Communauté (Alfaida)"
        ],
        notIncluded: ["Rapport SCI Complet", "Mentor IA Stratégique", "Workshops Personnalisés"],
        cta: "Essayer Librement",
        color: "slate",
        icon: "🌱"
      },
      {
        name: "Parcours Bourse",
        price: "Gratuit*",
        annualPrice: "Gratuit",
        annualNote: "Période de maturation requise",
        period: "Étudiant / Chercheur",
        popular: true,
        highlight: true,
        desc: "L'écosystème génératif complet pour bâtir votre identité.",
        features: [
          "Moteur Diagnostic complet en 7 étapes",
          "Mentor Stratégique IA Généré (Né du SCI)",
          "Workshops Personnalisés à 80% (Post-Diagnostic)",
          "Génération de Roadmap Dynamique (18 mois)",
          "Déblocage des Diplômes après 90 jours",
          "Simulations Stratégiques pour Scorecard"
        ],
        notIncluded: ["Documents Immédiats", "Consultant Humain Dédié 1:1"],
        cta: "Activer ma Bourse",
        color: "emerald",
        icon: "🎓"
      },
      {
        name: "Autorité Élite",
        price: "45€",
        annualPrice: "160€/an",
        annualNote: "Support d'exécution avancé",
        period: "/ 3 mois",
        desc: "Pour ceux qui veulent commander le marché immédiatement.",
        features: [
          "Tout du Parcours Bourse",
          "Architecture Documentaire Immédiate",
          "Accès Experts IA Spécialisés",
          "Archives du Savoir (Filtrées)",
          "Validation Humaine de la Roadmap",
          "Certification d'Autorité Premium"
        ],
        notIncluded: ["Formation Corporate Sur-mesure"],
        cta: "Prendre l'Autorité",
        color: "blue",
        icon: "💎"
      }
    ],
    extras: {
      title: "Compléments Stratégiques",
      subtitle: "Personnalisez votre parcours avec des interventions d'experts ciblées.",
      items: [
        { name: "Mission Stratégique Unique", desc: "Mission exécutive haute pression", price: "99€" },
        { name: "Session d'Audit Profond", desc: "1:1 avec Consultant Senior", price: "199€" },
        { name: "Architecture CV", desc: "Réécriture ATS professionnelle", price: "79€" },
      ]
    },
    paymentMethods: {
      title: "Paiement Sécurisé & Flexible",
      options: ["Virement Bancaire", "Carte Internationale", "Facturation Entreprise"]
    },
    paymentNote: "Toutes les transactions sont sécurisées par cryptage de grade militaire."
  },
  ar: {
    badge: "الاستثمار",
    title: "خطط الأسعار",
    subtitle: "اختر مستوى الدعم الذي يناسب أهدافك المهنية.",
    plans: [
      {
        name: "الباقة التجريبية",
        price: "مجاناً",
        annualPrice: "مجاناً",
        annualNote: "لا تتطلب بطاقة ائتمان",
        period: "مجانًا بالكامل",
        desc: "اختبر قوة المحرك عبر استخراج أولي لمهاراتك.",
        features: [
          "الملف المهني المجاني",
          "تحليل السيرة الذاتية (ملخص)",
          "اقتراحات ورش العمل",
          "خارطة طريق استراتيجية أولية",
          "دخول مجتمع الفايدة"
        ],
        notIncluded: ["تقرير SCI الكامل", "المستشار الاستراتيجي الذكي", "ورش عمل مخصصة بنسبة 80%"],
        cta: "ابدأ تجربتك المجانية",
        color: "slate",
        icon: "🌱"
      },
      {
        name: "مسار المنحة",
        price: "مجاني*",
        annualPrice: "مجاناً",
        annualNote: "تتطلب فترة نضج الخبرة",
        period: "خريج / باحث عن عمل",
        popular: true,
        highlight: true,
        desc: "النظام المولّد بالكامل لأولئك الذين يبنون هويتهم الأولى.",
        features: [
          "محرك التشخيص الكامل بـ 7 مراحل",
          "توليد مستشار استراتيجي ذكي (نتاج SCI)",
          "ورش عمل مخصصة بنسبة 80% (بعد التشخيص)",
          "توليد خارطة طريق ديناميكية (18 شهراً)",
          "فتح الاعتمادات الرسمية بعد 90 يوماً",
          "مهام محاكاة للحصول على سكور الأداء"
        ],
        notIncluded: ["استخراج الوثائق الفورية", "مستشار بشري مخصص 1:1"],
        cta: "تفعيل المنحة الاستراتيجية",
        color: "emerald",
        icon: "🎓"
      },
      {
        name: "سلطة النخبة",
        price: "٤٥$",
        annualPrice: "١٦٠$/سنة",
        annualNote: "دعم تنفيذ متقدم",
        period: "/ ٣ أشهر",
        desc: "لأولئك المستعدين لقيادة السوق بقوة فورية.",
        features: [
          "كل ما في مسار المنحة",
          "هندسة الوثائق الاستراتيجية الفورية",
          "وصول لخبراء الذكاء الاصطناعي المتخصصين",
          "أرشيف المعرفة (مفلتر حسب الفجوات)",
          "تصديق بشري على خارطة الطريق",
          "شهادة سلطة تنفيذية بريميوم"
        ],
        notIncluded: ["تدريب مؤسسي مخصص"],
        cta: "امتلاك السلطة المهنية",
        color: "blue",
        icon: "💎"
      }
    ],
    extras: {
      title: "إضافات استراتيجية",
      subtitle: "خصص مسار نموك عبر تدخلات الخبراء المستهدفة.",
      items: [
        { name: "مهمة استراتيجية واحدة", desc: "مهمة تنفيذية تحت الضغط", price: "$99" },
        { name: "جلسة تدقيق معمق", desc: "1:1 مع مستشار أول", price: "$199" },
        { name: "هندسة السيرة الذاتية", desc: "إعادة كتابة مهنية متوافقة مع ATS", price: "$79" },
      ]
    },
    paymentMethods: {
      title: "دفع آمن ومرن",
      options: ["تحويل بنكي (تونس وعالمياً)", "بطاقة دولية", "فوترة شركات"]
    },
    paymentNote: "جميع المعاملات مؤمنة بتشفير من الدرجة العسكرية."
  }
};

// ─── COMMITMENT AGREEMENT ────────────────────────────────────────────────────────
export const CONTRACT = {
  en: {
    title: "Scholarship Commitment",
    subtitle: "Reference: MATC-SCHOLAR-2026 / GEN-01 | Strategic Growth Pledge",
    docTitle: "Strategic Scholarship Agreement",
    parties: "Between: MA-TRAINING-CONSULTING (Grantor) and: Recipient ({{client}})",
    clauses: [
      { title: "Article 1: The Generative Mission", text: "MATC provides a full AI-driven diagnostic engine to generate your identity. You commit to 90 days of active workshop participation to validate this generated data." },
      { title: "Article 2: Diagnostic DNA Usage", text: "Your diagnostic results act as the source code for all modules. You agree that authority documents are only born after the required maturation period." },
      { title: "Article 3: Ownership of Intelligence", text: "All AI models, simulation environments, and generated roadmaps remain the intellectual property of MATC." },
      { title: "Article 4: Validation Rule", text: "Official credentials (SCI, Letter of Rec) are earned through participation, not just registration. Maturation protects the value of your future authority." },
      { title: "Article 5: Formal Activation", text: "Downloading and signing this pledge activates your scholarship status and the AI diagnostic engine." },
    ],
    cta: "Sign Scholarship Pledge (PDF)",
    nameLabel: "Full Name",
    namePlaceholder: "As per your legal ID",
    dateLabel: "Activation Date",
    nameRequired: "Identification required for enrollment",
    legalNote: "Note: Signing this document is a formal commitment to the 90-day growth maturation process.",
  },
  fr: {
    title: "Engagement de Bourse",
    subtitle: "Référence : MATC-BOURSE-2026 / GEN-01 | Engagement de Croissance",
    docTitle: "Accord de Bourse Stratégique",
    parties: "Entre : MA-TRAINING-CONSULTING (Donneur) et : Récipiendaire ({{client}})",
    clauses: [
      { title: "Article 1 : La Mission Générative", text: "MATC fournit un moteur diagnostic IA complet. Vous vous engagez à 90 jours de participation active pour valider ces données générées." },
      { title: "Article 2 : Utilisation de l'ADN Diagnostic", text: "Vos résultats servent de code source à tous les modules. L'autorité officielle n'est débloquée qu'après la maturation requise." },
      { title: "Article 3 : Propriété de l'Intelligence", text: "Tous les modèles d'IA et roadmaps générés restent la propriété intellectuelle exclusive de MATC." },
      { title: "Article 4 : Règle de Validation", text: "Les documents officiels se méritent par la participation. La maturation protège la valeur de votre future autorité." },
      { title: "Article 5 : Activation Formelle", text: "La signature de cet engagement active votre statut de boursier et le moteur diagnostic IA." },
    ],
    cta: "Signer l'Engagement Bourse (PDF)",
    nameLabel: "Nom Complet",
    namePlaceholder: "Selon votre pièce d'identité",
    dateLabel: "Date d'Activation",
    nameRequired: "Inscription requise pour activation",
    legalNote: "Note : Ce document constitue un engagement formel envers le processus de maturation de 90 jours.",
  },
  ar: {
    title: "تعهد المنحة الاستراتيجية",
    subtitle: "مرجع: MATC-SCHOLAR-2026 / GEN-01 | ميثاق النمو المهني",
    docTitle: "اتفاقية المنحة التدريبية",
    parties: "بين: مكتب MA-TRAINING-CONSULTING (المانح) و: المستفيد ({{client}})",
    clauses: [
      { title: "المادة الأولى: المهمة التوليدية", text: "يوفر المكتب محرك تشخيص ذكي لتوليد هويتك المهنية. وتلتزم أنت بالمشاركة الفعالة في ورش العمل لمدة 90 يوماً لتصديق هذه البيانات." },
      { title: "المادة الثانية: استخدام الحمض النووي للتشخيص", text: "نتائج تشخيصك هي الكود المصدري لكل الوحدات التدريبية. لا تصدر وثائق السلطة الرسمية إلا بعد اكتمال فترة النضج المطلوبة." },
      { title: "المادة الثالثة: ملكية الذكاء والمنهجية", text: "تظل جميع نماذج الذكاء الاصطناعي وخرائط الطريق المولدة ملكية فكرية حصرية لمكتب MATC." },
      { title: "المادة الرابعة: قاعدة التحقق", text: "الوثائق الرسمية تكتسب بالمشاركة الحقيقية وليس بمجرد التسجيل. فترة النضج تحمي قيمة سلطتك المهنية المستقبلية." },
      { title: "المادة الخامسة: التفعيل الرسمي", text: "توقيع هذا الميثاق يعتبر تفعيلاً رسمياً لوضع المنحة ولدخول محرك التشخيص الاستراتيجي." },
    ],
    cta: "توقيع تعهد المنحة (PDF)",
    nameLabel: "الاسم الكامل",
    namePlaceholder: "كما في الهوية الرسمية",
    dateLabel: "تاريخ التفعيل",
    nameRequired: "التعريف بالهوية مطلوب لتفعيل المنحة",
    legalNote: "ملاحظة: توقيع هذا المستند هو التزام رسمي بعملية نضج الخبرة التي تستغرق 90 يوماً.",
  },
};

// ─── FINAL CTA ───────────────────────────────────────────────────────────────────
export const FINAL_CTA = {
  en: {
    title: "Execute Your Future Now",
    subtitle: "Activate the diagnostic engine and generate your path to market authority.",
    cta: "Start Diagnostic Engine",
    note: "The Scholarship path is currently open for eligible job seekers."
  },
  fr: {
    title: "Exécutez Votre Avenir Maintenant",
    subtitle: "Activez le moteur diagnostic et générez votre chemin vers l'autorité marché.",
    cta: "Lancer le Moteur Diagnostic",
    note: "Le parcours Bourse est ouvert aux chercheurs d'emploi éligibles."
  },
  ar: {
    title: "فجّر طاقاتك المهنية الآن",
    subtitle: "فعّل محرك التشخيص وولّد مسارك نحو السلطة المهنية في سوق العمل.",
    cta: "تفعيل محرك التشخيص",
    note: "مسار المنحة مفتوح حالياً للباحثين عن فرصة عمل المؤهلين."
  }
};
